### ISSUE TITLE
What is the Random Seed Represent?

### ISSUE THREAD

**Issue by akmal871026** [PyTomography/slicer_spect_recon#15]
Dear @ObedDzik @lukepolson @ahxmeds ,

May I know what the Random Seed Represents?

What is the number should i put?

![image](https://github.com/user-attachments/assets/c114bbcc-c45e-4188-873c-ffc1e651cc30)

**Comment by ObedDzik** [comment]
Any random whole number should be fine. It is just to ensure reproducibility of results.

**Comment by lukepolson** [comment]
SIMIND data gives you the mean number of counts per each detector bin. To generate clinically realistic data, you need to generate Poisson counts for each bin. The random seed is the seed used in the random number generator when getting this Poisson data. It allows for reproducibility since the same seed will give you the same random numbers.

**Comment by akmal871026** [comment]
Ok, tq luke. Then what should number should I put? Is it enough I put 1? Or
10?

**Comment by lukepolson** [comment]
Any number is fine. It's more for scientific reproducibility: i.e. somebody with your exact SIMIND data should be able to generate the same noisy data as you. So it's a good idea to keep track of whatever number you use.

**Comment by akmal871026** [comment]
ok Tq Dr. Luke..

May I get your email address?


*___________________________________*

*MOHD AKMAL BIN MASUD*

H/P: +60143321631
